### PR TITLE
Updated api for Collections

### PR DESCRIPTION
**Pull request by jeremyjs**
Noticed the .getCollection method wasn't working, so I fixed it quick.
Medium must have updated their api.

### CODE REVIEW

**Comment by jjman505** [comment]
Btw, not sure which coffeescript compiler you're using, so I didn't push the compiled code. I assume it will need to be recompiled to work on npm.

**Comment by philplckthun** [comment]
Thanks! I haven't touched this in a while, but I'll merge this asap

**Comment by popey456963** [comment]
@philpl Any update? :)

**Comment by philpl** [comment]
Hiya, i went ahead and merged it but I unfortunately don’t have time to maintain this any longer. If anyone would like to take it over, possibly with a rewrite, I’m happy to add you to the project

**Pull request merged**
